PLUGINOBJECTS = ofxsThreadSuite.o tinythread.o RunScript.o
PLUGINNAME = RunScript
RESOURCES = fr.inria.openfx.RunScript.png fr.inria.openfx.RunScript.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

