PLUGINOBJECTS = SeExpr.o SeNoise.o ofxsGenerator.o ofxsRectangleInteract.o PluginRegistration.o ofxsRamp.o ofxsTransformInteract.o
PLUGINNAME = SeExpr
RESOURCES = fr.inria.openfx.SeExpr.png fr.inria.openfx.SeExpr.svg

include ../Makefile.master

CXXFLAGS += $(SEEXPR_CXXFLAGS)
LINKFLAGS += $(SEEXPR_LINKFLAGS)
