PLUGINOBJECTS = \
	ReadPFM.o WritePFM.o \
	PluginRegistration.o \
	GenericReader.o GenericWriter.o GenericOCIO.o SequenceParsing.o

PLUGINNAME = PFM

RESOURCES = \
fr.inria.openfx.ReadPFM.png \fr.inria.openfx.ReadPFM.svg \fr.inria.openfx.WritePFM.png \fr.inria.openfx.WritePFM.svg  

include ../Makefile.master
