PATHTOROOT = ../openfx/Support

include $(PATHTOROOT)/Plugins/Makefile.master

CXXFLAGS += -DOFX_EXTENSIONS_VEGAS -DOFX_EXTENSIONS_NUKE -DOFX_EXTENSIONS_NATRON -DOFX_EXTENSIONS_TUTTLE -I../IOSupport

# Comment the following two lines to disable OpenColorIO support
CXXFLAGS += `pkg-config --cflags OpenColorIO` -DIO_USING_OCIO
LINKFLAGS += `pkg-config --libs OpenColorIO`
