PLUGINOBJECTS = \
	MagickText.o \
	ofxsOGLTextRenderer.o \
	ofxsOGLFontData.o \
	ofxsRectangleInteract.o \
	PluginRegistration.o \

PLUGINNAME = Magick

RESOURCES = \
fr.inria.openfx.MagickText.png \
fr.inria.openfx.MagickText.svg \

include ../Makefile.master

CXXFLAGS += $(MAGICK_CXXFLAGS)
LINKFLAGS += $(MAGICK_LINKFLAGS)
