PLUGINOBJECTS = OCIOCDLTransform.o OCIOColorSpace.o OCIOFileTransform.o OCIOLogConvert.o OCIOLookTransform.o GenericOCIO.o PluginRegistration.o
PLUGINNAME = OCIO

include ../Makefile.master

OIIO_HOME ?= /usr
