PLUGINOBJECTS = CTLTransform.o
PLUGINNAME = CTL
#RESOURCES = fr.inria.CTLTransform.png fr.inria.CTLTransform.svg

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master

CXXFLAGS += $(CTL_CXXFLAGS)
LINKFLAGS += $(CTL_LINKFLAGS)
